//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website.Admin
{
    public partial class AdminMaster
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager sm;
        protected global::System.Web.UI.WebControls.Literal litAdminName;
    }
}
