//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website.Admin
{
    public partial class AdminDashboardPage
    {
        protected global::System.Web.UI.WebControls.Literal litToday;
        protected global::System.Web.UI.WebControls.Literal litTotalOrders;
        protected global::System.Web.UI.WebControls.Literal litPending;
        protected global::System.Web.UI.WebControls.Literal litTodayRevenue;
        protected global::System.Web.UI.WebControls.Literal litDeliveredRevenue;
        protected global::System.Web.UI.WebControls.Literal litProducts;
        protected global::System.Web.UI.WebControls.Literal litCustomers;
        protected global::System.Web.UI.WebControls.Repeater rptRecent;
    }
}
