//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website.Admin
{
    public partial class AdminOrderDetailPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlOrder;
        protected global::System.Web.UI.WebControls.Literal litOrderNumber;
        protected global::System.Web.UI.WebControls.Literal litDate;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.TextBox txtNote;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Literal litRecipient;
        protected global::System.Web.UI.WebControls.Literal litPhone;
        protected global::System.Web.UI.WebControls.Literal litZone;
        protected global::System.Web.UI.WebControls.Literal litAddress;
        protected global::System.Web.UI.WebControls.Panel pnlLandmark;
        protected global::System.Web.UI.WebControls.Literal litLandmark;
        protected global::System.Web.UI.WebControls.Panel pnlGift;
        protected global::System.Web.UI.WebControls.Literal litGift;
        protected global::System.Web.UI.WebControls.Panel pnlCustNote;
        protected global::System.Web.UI.WebControls.Literal litCustNote;
        protected global::System.Web.UI.WebControls.Repeater rptHistory;
        protected global::System.Web.UI.WebControls.Repeater rptItems;
        protected global::System.Web.UI.WebControls.Literal litSubtotal;
        protected global::System.Web.UI.WebControls.Literal litFee;
        protected global::System.Web.UI.WebControls.Literal litTotal;
    }
}
