//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website.Admin
{
    public partial class AdminProductEditPage
    {
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litHeading;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.TextBox txtNameAr;
        protected global::System.Web.UI.WebControls.TextBox txtNameEn;
        protected global::System.Web.UI.WebControls.TextBox txtDescAr;
        protected global::System.Web.UI.WebControls.TextBox txtDescEn;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.TextBox txtBasePrice;
        protected global::System.Web.UI.WebControls.TextBox txtWeightNoteAr;
        protected global::System.Web.UI.WebControls.TextBox txtWeightNoteEn;
        protected global::System.Web.UI.WebControls.TextBox txtSortOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.CheckBox chkBestSeller;
        protected global::System.Web.UI.WebControls.CheckBox chkNew;
        protected global::System.Web.UI.WebControls.TextBox txtWeightOptions;
        protected global::System.Web.UI.WebControls.TextBox txtFlavors;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnDelete;
    }
}
