//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website.Account
{
    public partial class ForgotPasswordPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlRequest;
        protected global::System.Web.UI.WebControls.Panel pnlRequestDone;
        protected global::System.Web.UI.WebControls.Panel pnlRequestForm;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnRequest;
        protected global::System.Web.UI.WebControls.Panel pnlDevLink;
        protected global::System.Web.UI.WebControls.HyperLink lnkDev;
        protected global::System.Web.UI.WebControls.Panel pnlReset;
        protected global::System.Web.UI.WebControls.Panel pnlResetInvalid;
        protected global::System.Web.UI.WebControls.Panel pnlResetDone;
        protected global::System.Web.UI.WebControls.Panel pnlResetForm;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirm;
        protected global::System.Web.UI.WebControls.Button btnReset;
    }
}
