//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website
{
    public partial class CheckoutPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlSavedAddresses;
        protected global::System.Web.UI.WebControls.DropDownList ddlSavedAddress;
        protected global::System.Web.UI.WebControls.TextBox txtRecipient;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.DropDownList ddlZone;
        protected global::System.Web.UI.WebControls.TextBox txtDetails;
        protected global::System.Web.UI.WebControls.TextBox txtLandmark;
        protected global::System.Web.UI.WebControls.CheckBox chkSaveAddress;
        protected global::System.Web.UI.WebControls.TextBox txtGift;
        protected global::System.Web.UI.WebControls.TextBox txtNote;
        protected global::System.Web.UI.WebControls.Repeater rptItems;
        protected global::System.Web.UI.WebControls.Literal litSubtotal;
        protected global::System.Web.UI.WebControls.Literal litDeliveryFee;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;
    }
}
