//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website
{
    public partial class DefaultPage
    {
        /// <summary>rptFeatured control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptFeatured;
    }
}
