//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website
{
    public partial class MenuPage
    {
        /// <summary>rptTabs control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptTabs;

        /// <summary>rptProducts control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptProducts;

        /// <summary>litCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCount;

        /// <summary>pnlEmpty control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
