//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website
{
    public partial class ProductPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlProduct;
        protected global::System.Web.UI.WebControls.Literal litCrumb;
        protected global::System.Web.UI.WebControls.Literal litBadge;
        protected global::System.Web.UI.WebControls.Literal litCat;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litDesc;
        protected global::System.Web.UI.WebControls.Literal litPrice;
        protected global::System.Web.UI.WebControls.Literal litPriceNote;
        protected global::System.Web.UI.WebControls.Panel pnlWeights;
        protected global::System.Web.UI.WebControls.Repeater rptWeights;
        protected global::System.Web.UI.WebControls.Panel pnlFlavors;
        protected global::System.Web.UI.WebControls.Repeater rptFlavors;
        protected global::System.Web.UI.WebControls.HiddenField hfWeightId;
        protected global::System.Web.UI.WebControls.HiddenField hfQty;
        protected global::System.Web.UI.WebControls.HiddenField hfFlavorAr;
        protected global::System.Web.UI.WebControls.HiddenField hfFlavorEn;
        protected global::System.Web.UI.WebControls.Button btnAddToCart;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Panel pnlLongDesc;
        protected global::System.Web.UI.WebControls.Literal litLongDesc;
        protected global::System.Web.UI.WebControls.Panel pnlRelated;
        protected global::System.Web.UI.WebControls.Repeater rptRelated;
    }
}
