//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website.Account
{
    public partial class MyAccountPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Panel pnlErr;
        protected global::System.Web.UI.WebControls.Literal litErr;

        protected global::System.Web.UI.WebControls.Panel pnlOrders;
        protected global::System.Web.UI.WebControls.Panel pnlNoOrders;
        protected global::System.Web.UI.WebControls.Repeater rptOrders;

        protected global::System.Web.UI.WebControls.Panel pnlAddresses;
        protected global::System.Web.UI.WebControls.Repeater rptAddresses;
        protected global::System.Web.UI.WebControls.Literal litAddrFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfAddrId;
        protected global::System.Web.UI.WebControls.TextBox txtAddrLabel;
        protected global::System.Web.UI.WebControls.DropDownList ddlAddrZone;
        protected global::System.Web.UI.WebControls.TextBox txtAddrDetails;
        protected global::System.Web.UI.WebControls.TextBox txtAddrLandmark;
        protected global::System.Web.UI.WebControls.TextBox txtAddrPhone;
        protected global::System.Web.UI.WebControls.CheckBox chkAddrDefault;
        protected global::System.Web.UI.WebControls.Button btnAddrSave;
        protected global::System.Web.UI.WebControls.Button btnAddrCancel;

        protected global::System.Web.UI.WebControls.Panel pnlProfile;
        protected global::System.Web.UI.WebControls.TextBox txtProfileName;
        protected global::System.Web.UI.WebControls.TextBox txtProfileEmail;
        protected global::System.Web.UI.WebControls.TextBox txtProfilePhone;
        protected global::System.Web.UI.WebControls.Button btnProfileSave;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPw;
        protected global::System.Web.UI.WebControls.TextBox txtNewPw;
        protected global::System.Web.UI.WebControls.TextBox txtNewPwConfirm;
        protected global::System.Web.UI.WebControls.Button btnChangePw;
    }
}
