//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website
{
    public partial class OrderConfirmationPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlOrder;
        protected global::System.Web.UI.WebControls.Literal litOrderNumber;
        protected global::System.Web.UI.WebControls.Literal litRecipient;
        protected global::System.Web.UI.WebControls.Literal litPhone;
        protected global::System.Web.UI.WebControls.Literal litZone;
        protected global::System.Web.UI.WebControls.Literal litAddress;
        protected global::System.Web.UI.WebControls.Panel pnlLandmark;
        protected global::System.Web.UI.WebControls.Literal litLandmark;
        protected global::System.Web.UI.WebControls.Panel pnlGift;
        protected global::System.Web.UI.WebControls.Literal litGift;
        protected global::System.Web.UI.WebControls.Repeater rptItems;
        protected global::System.Web.UI.WebControls.Literal litSubtotal;
        protected global::System.Web.UI.WebControls.Literal litFee;
        protected global::System.Web.UI.WebControls.Literal litTotal;
    }
}
