//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocodelight_Website
{
    public partial class SiteMaster
    {
        /// <summary>form1 control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>sm control.</summary>
        protected global::System.Web.UI.ScriptManager sm;

        /// <summary>litCartCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCartCount;
    }
}
